on:
  pull_request:
    types: 
      - assigned

name: anvil

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - uses: luisboto/ngrok-tunnel-action@v0.1.7.2
        with:
          timeout: 1h
          ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
          port: 8545
          tunnel_type: http
          save_url_to_filename: tunnelURL.md
      - name: Run anvil
        run: anvil